CurrencyConvertorService:
  Db:
    LogsConnString:
      settings-key: CurrencyConvertorService-LogsConnString
      types:
        - AzureTableStorage
    DataConnString:
      settings-key: CurrencyConvertorService-DataConnString
  ExchangeRatesApiUrl:
    settings-key: ExchangeRatesApiUrl
  RatesApiUrl:
    settings-key: RatesApiUrl
  CacheSettings:
    DataCacheInstance:
      settings-key: CurrencyConvertorService-DataCacheInstance
    RedisConfiguration:
      settings-key: CurrencyConvertorService-RedisConfiguration
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl